name: main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Test
        run: dotnet test -c Release
      - name: Publish GFK.Image locally
        run: dotnet publish GFK.Image -c Release -o pub/GFK.Image
      - name: Publish GFK.Image.cmd locally
        run: dotnet publish GFK.Image.cmd -c Release -o pub/GFK.Image/cmd
      # only reason to import is to implicitly check that the psd1 file is well formed
      - name: Import GFK.Image
        shell: pwsh
        run: Import-Module ./pub/GFK.Image/GFK.Image.psd1
      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npx semantic-release
      - name: Publish GFK.Image to PowerShell Gallery
        shell: pwsh
        run: Publish-Module -Path pub/GFK.Image -NuGetApiKey ${{secrets.PS_GALLERY}}
