name: PSGallery

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish GFK.Image locally
        run: dotnet publish GFK.Image -c Release -o pub/GFK.Image
      - name: Publish cmd locally
        run: dotnet publish cmd -c Release -o pub/GFK.Image/cmd
      - name: Publish to PowerShell Gallery
        run: Publish-Module -Path pub/GFK.Image -NuGetApiKey {{secrets.PS_GALLERY}}
        shell: pwsh