name: Tests

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Test
        run: dotnet test
      - name: Publish GFK.Image
        run: dotnet publish GFK.Image -o pub/GFK.Image
      - name: Publish GFK.Image.cmd
        run: dotnet publish GFK.Image.cmd -o pub/GFK.Image/cmd
      # only reason to import is to implicitly check that the psd1 file is well formed
      - name: Import GFK.Image
        shell: pwsh
        run: Import-Module ./pub/GFK.Image/GFK.Image.psd1
