name: tests

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Test
        run: dotnet test
      - name: Publish module locally
        run: dotnet publish -o pub/GFK.Image
      - name: Test module manifest
        shell: pwsh
        run: Test-ModuleManifest pub/GFK.Image/GFK.Image.psd1
