name: Test

on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: test
        run: dotnet test
      - name: publish GFK.Image
        run: dotnet publish GFK.Image -o pub
      - name: publish GFK.Image.cmd
        run: dotnet publish GFK.Image.cmd -o pub/GFK.Image/cmd
      - name: import GFK.Image
        run: Import-Module pub/GFK.Image/GFK.Image.psd1