name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Test
        run: dotnet test
      - name: Publish GFK.Image
        run: dotnet publish GFK.Image -o pub
      - name: Publish GFK.Image.cmd
        run: dotnet publish GFK.Image.cmd -o pub/GFK.Image/cmd